# Generated by Django 3.2.5 on 2021-07-31 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='website_url',
            new_name='website',
        ),
    ]
