# Generated by Django 3.2.5 on 2021-07-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='amenities',
            field=models.ManyToManyField(to='events.Amenity'),
        ),
    ]
