# Generated by Django 3.2.5 on 2021-07-31 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventspeaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspeaker',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
    ]
