# Generated by Django 3.2.5 on 2021-07-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventspeaker_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
