# Generated by Django 3.2.5 on 2021-07-31 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_amenity_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 6, 26, 734752, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 15, 6, 30, 722272, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
