# Generated by Django 3.2.5 on 2021-08-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20210804_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
