# Generated by Django 3.2.5 on 2021-08-05 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210804_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 8, 5, 12, 2, 5, 500142, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
