# Generated by Django 3.2.5 on 2021-08-06 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20210806_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimage',
            name='event',
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.eventreview'),
            preserve_default=False,
        ),
    ]
