# Generated by Django 3.2.5 on 2021-08-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_featuredlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredlocation',
            name='image',
            field=models.ImageField(null=True, upload_to='events/locations'),
        ),
    ]
