# Generated by Django 3.2.5 on 2021-08-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_featuredlocation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredlocation',
            name='image',
            field=models.ImageField(default=1, upload_to='events/locations'),
            preserve_default=False,
        ),
    ]
