# Generated by Django 3.2.5 on 2021-08-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_featuredlocation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='events/categories'),
            preserve_default=False,
        ),
    ]
