# Generated by Django 3.2.5 on 2021-08-10 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_userticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='userticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
