# Generated by Django 3.2.5 on 2021-08-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_eventsave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['s_time']},
        ),
        migrations.AlterField(
            model_name='event',
            name='amenities',
            field=models.ManyToManyField(null=True, to='events.Amenity'),
        ),
    ]
