# Generated by Django 3.2.5 on 2021-08-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20210814_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='events.Amenity'),
        ),
    ]
