# Generated by Django 3.2.7 on 2021-09-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20210909_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_currency',
            field=models.CharField(blank=True, choices=[('NGN', 'Nigerian naira'), ('USD', 'United States Dollar'), ('GBR', 'British Pounds'), ('EUR', 'Euro')], max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.FloatField(blank=True),
        ),
    ]
