# Generated by Django 3.2.7 on 2021-09-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team_id',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='team_name',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='team_phone',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
