# Generated by Django 3.2.7 on 2021-09-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_eventreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
