# Generated by Django 3.2.7 on 2021-09-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_auto_20210910_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userticket',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='userticket',
            name='email',
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.FloatField(default=0),
        ),
    ]
