# Generated by Django 3.2.7 on 2021-09-10 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_auto_20210910_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 12, 4, 30, 31454, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 10, 12, 4, 36, 157029, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='team_id',
            field=models.CharField(blank=True, default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='team_name',
            field=models.CharField(blank=True, default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='team_phone',
            field=models.CharField(blank=True, default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
