# Generated by Django 3.2.7 on 2021-09-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_alter_event_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket_currency',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='event',
            name='inform_tools_conf',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
