# Generated by Django 3.2.7 on 2021-09-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_auto_20210910_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='team_phone',
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_currency',
            field=models.CharField(blank=True, choices=[('NGN', 'Nigerian naira'), ('USD', 'United States Dollar'), ('GBR', 'British Pounds'), ('EUR', 'Euro')], max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.FloatField(default=0),
        ),
    ]
