# Generated by Django 3.2.7 on 2021-09-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_alter_event_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
